# Generated by Django 5.1.4 on 2024-12-28 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='song',
            name='lyrics',
        ),
        migrations.AddField(
            model_name='song',
            name='audio_url',
            field=models.URLField(default='https://example.com/default-audio.mp3'),
        ),
        migrations.AddField(
            model_name='song',
            name='cover_url',
            field=models.URLField(default='https://example.com/default-cover.jpg'),
        ),
        migrations.CreateModel(
            name='SongSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('song1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='music.song')),
                ('song2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_from', to='music.song')),
            ],
            options={
                'unique_together': {('song1', 'song2')},
            },
        ),
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked', models.BooleanField(default=False)),
                ('favorited', models.BooleanField(default=False)),
                ('play_count', models.IntegerField(default=0)),
                ('last_played', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'song')},
            },
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
